import mongoose from "mongoose";

const CustomTradeSchema = new mongoose.Schema(
  {
    firstName: {
      type: String,
      required: true,
      min: 2,
      max: 100,
    },
    lastName: {
      type: String,
      required: true,
      min: 2,
      max: 100,
    },
    address: {
      type: String,
      required: true,
      max: 50,
    },
    acquisition: String,
    arv: String,
    assignedAgent: String,
    bestPhoneNumber: String,
    builtYear: String,    
    city: String,
    comps: String,
    county: String,
    email: String,
    furnace: String,
    garage: String,
    leadStatus: String,
    liens: String,
    lotSize: String, 
    monthlyPayments: String,
    mortgage: String, 
    ownedFor: String,
    owed: String,
    paidOff: String,
    performance: String,
    phoneNumber: String,
    pool: String,
    price: String,
    propertySize: String,
    repairs: String,
    roof: String,
    sellingReason: String, 
    state: String,  
    tenants: String,
    timeLine: String,
    timeToSell: String,
    type: String,
    unitNumber: String,
    url: String,
    waterHeater: String,    
    zipCode: String, 
    notes: String,
    audioMetadata: {
      title: String,
      duration: Number,
      format: String,
      bitrate: Number,
      sampleRate: Number,
      channels: Number,
      fileSize: Number,
      fileUrl: String,
    },
  },
  { timestamps: true }
);

const CustomTrade = mongoose.model("CustomTrade", CustomTradeSchema);
export default CustomTrade;
